### ISSUE TITLE
Image hight missing on zooming when using with img-responsive

### ISSUE THREAD

**Issue by lyquocnam** [stephan281094/meteor-zoom#2]
![2 pool network - btc investment20160817202506](https://cloud.githubusercontent.com/assets/8347826/17737854/2e085d2a-64b9-11e6-96e7-ea4329b5eddf.gif)

**Comment by stephan281094** [comment]
Hi there. Thank you for contributing!
We're now relying on [spinningarrow/zoom-vanilla.js](https://github.com/spinningarrow/zoom-vanilla.js) rather than [fat/zoom.js](https://github.com/fat/zoom.js). Perhaps this could have resolved the issue.

However, I'd like to note that Meteor-zoom is simply a wrapper, meaning that it doesn't contain any logic to get the zooming functionality to work. If you noticed an issue with the zoom library, please create an issue at [spinningarrow/zoom-vanilla.js](https://github.com/spinningarrow/zoom-vanilla.js) instead. Thanks.
